# Generated by Django 2.0.3 on 2018-03-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiotherapy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiotherapy',
            name='details',
        ),
    ]
