# Generated by Django 2.0.3 on 2018-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='religion',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
