# Generated by Django 2.0.12 on 2023-11-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0002_auto_20180316_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('cardiac', models.BooleanField(default=False)),
                ('liver', models.BooleanField(default=False)),
                ('kedney', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity')),
            ],
        ),
    ]
