# Generated by Django 2.0.3 on 2018-03-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0005_auto_20180316_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bsa',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diseaseCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='er_pr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='histopathology',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ihc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ps',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stage',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tnm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, max_length=5),
        ),
    ]
