# Generated by Django 2.0.3 on 2018-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0009_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='identity_fk',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
