# Generated by Django 2.0.3 on 2018-03-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0011_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='identity_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity'),
        ),
    ]
