# Generated by Django 2.0.3 on 2018-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0012_auto_20180321_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
