# Generated by Django 2.0.3 on 2018-03-22 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientbasicinfo', '0013_identity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
