# Generated by Django 2.0.3 on 2018-03-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemotherapy', '0002_auto_20180320_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(blank=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('day1', models.CharField(blank=True, max_length=50)),
                ('day2', models.CharField(blank=True, max_length=50)),
                ('day3', models.CharField(blank=True, max_length=50)),
                ('day4', models.CharField(blank=True, max_length=50)),
                ('day5', models.CharField(blank=True, max_length=50)),
                ('day8', models.CharField(blank=True, max_length=50)),
                ('day15', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NactCycle',
            fields=[
                ('cycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tables.Cycle')),
                ('nact_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemotherapy.ChemoTherapy')),
            ],
            bases=('tables.cycle',),
        ),
    ]
