# Generated by Django 2.0.3 on 2018-03-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiotherapy', '0002_remove_radiotherapy_details'),
        ('tables', '0002_actcycle_concurrentcycle_palliativecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioTherapyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=50)),
                ('nameoffield', models.CharField(blank=True, max_length=50)),
                ('fieldsize', models.FloatField()),
                ('tumordose', models.CharField(blank=True, max_length=50)),
                ('seperation', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BrachyChart',
            fields=[
                ('radiotherapychart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tables.RadioTherapyChart')),
                ('brachy_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiotherapy.RadioTherapy')),
            ],
            bases=('tables.radiotherapychart',),
        ),
        migrations.CreateModel(
            name='CobaltChart',
            fields=[
                ('radiotherapychart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tables.RadioTherapyChart')),
                ('cobalt_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiotherapy.RadioTherapy')),
            ],
            bases=('tables.radiotherapychart',),
        ),
        migrations.CreateModel(
            name='LinacChart',
            fields=[
                ('radiotherapychart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tables.RadioTherapyChart')),
                ('linac_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiotherapy.RadioTherapy')),
            ],
            bases=('tables.radiotherapychart',),
        ),
    ]
