# Generated by Django 2.0.3 on 2018-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20180321_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('meaning', models.CharField(max_length=200)),
            ],
        ),
    ]
