# Generated by Django 2.0.3 on 2018-03-18 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientbasicinfo', '0007_bangla_dose_medicine_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('identity_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/history_file/%Y/%m/%d/%H/%M/%S/')),
                ('fnum', models.IntegerField(default=0)),
                ('name', models.CharField(default='name unavailable', max_length=100)),
                ('identity_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity')),
            ],
        ),
    ]
