# Generated by Django 2.0.3 on 2018-03-17 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientbasicinfo', '0007_bangla_dose_medicine_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('details', models.CharField(blank=True, max_length=50)),
                ('identity_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity')),
            ],
        ),
    ]
