# Generated by Django 2.0.3 on 2018-03-18 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientbasicinfo', '0007_bangla_dose_medicine_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('refferedDept', models.CharField(blank=True, max_length=200)),
                ('refferedConsultant', models.CharField(blank=True, max_length=200)),
                ('responseNote', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('noteNo', models.IntegerField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.Identity')),
            ],
        ),
    ]
