# Generated by Django 2.0.3 on 2018-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralnote',
            name='condition',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='referralnote',
            name='purpose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='referralnote',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='referralnote',
            name='responseNote',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
