# Generated by Django 2.0.3 on 2018-03-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientbasicinfo', '0008_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemoTherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=200)),
                ('tp_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.TreatmentPlan')),
            ],
        ),
    ]
