# Generated by Django 2.0.3 on 2018-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemotherapy', '0002_auto_20180320_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemotherapy',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
