# Generated by Django 2.0.3 on 2018-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeryhormone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormone',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='details',
            field=models.CharField(max_length=1000),
        ),
    ]
