# Generated by Django 2.0.3 on 2018-03-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientbasicinfo', '0008_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetedTherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Immunotherapy',
            fields=[
                ('targetedtherapy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='targetedtherapy.TargetedTherapy')),
                ('tp_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.TreatmentPlan')),
            ],
            bases=('targetedtherapy.targetedtherapy',),
        ),
        migrations.CreateModel(
            name='Tki',
            fields=[
                ('targetedtherapy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='targetedtherapy.TargetedTherapy')),
                ('tp_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientbasicinfo.TreatmentPlan')),
            ],
            bases=('targetedtherapy.targetedtherapy',),
        ),
    ]
